import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import MovieRow from "../components/MovieRow"

export const getStaticProps = async ()=>{
  const res =  await  fetch("https://api.themoviedb.org/3/genre/movie/list?api_key=c58c4ef409f00bd5da3e27540adf8816&language=en-US");
  const data = await res.json()

  return {
    props:{
      genres: data
    }
  }
}

export default function Home({genres}) {
  console.log(genres)
  return (
    <div className={styles.container}>
      <Head>
        <title>Movie Haus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <h2 className="text-3xl">Movie Haus </h2>
       <MovieRow titles={genres}/>
       
       
      </main>

      
    </div>
  )
}
