import Head from "next/head";
import styles from "../styles/Home.module.css";
import MovieRow from "../components/MovieRow";
import MovieBanner from "../components/MovieBanner";

export const getStaticProps = async () => {
  //multiple parallel fetch request
  const [crimeMovieRes, actionMovieRes, animationMovieRes] = await Promise.all([
    fetch(
      `https://api.themoviedb.org/3/discover/movie?api_key=c58c4ef409f00bd5da3e27540adf8816&with_genres=80`
    ),
    fetch(
      `https://api.themoviedb.org/3/discover/movie?api_key=c58c4ef409f00bd5da3e27540adf8816&with_genres=28`
    ),
    fetch(
      `https://api.themoviedb.org/3/discover/movie?api_key=c58c4ef409f00bd5da3e27540adf8816&with_genres=16`
    ),
  ]);
  const crimeMovieData = await crimeMovieRes.json();
  const actionMovieData = await actionMovieRes.json();
  const animeMovieData = await animationMovieRes.json();
  return {
    props: {
      crimeMovieData,
      actionMovieData,
      animeMovieData,
    },
  };
};

export default function Home({
  crimeMovieData,
  actionMovieData,
  animeMovieData,
}) {
  // console.log("request", crimeMovieData, actionMovieData, animeMovieData);
  return (
    <div className={styles.container}>
      <Head>
        <title>Movie Haus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className="text-3xl">Movie Haus </h2>
        <MovieBanner banner={actionMovieData} />

        <MovieRow movies={crimeMovieData} genre="Crime" />
        <MovieRow movies={animeMovieData} genre="Animation" />
        <MovieRow movies={actionMovieData} genre="Action" />
      </main>
    </div>
  );
}
